name: React CI/CD Pipeline

on:
  push:
    branches: [ master, main, feature-prod-details ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # This tells GitHub to run all 'run' commands inside the app1 folder
    defaults:
      run:
        working-directory: ./app1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # Tell the cache to look for the lockfile inside app1
          cache-dependency-path: ./app1/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build
        env:
          CI: false

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app1/build # We point to the build folder inside app1
          branch: gh-pages